### ISSUE TITLE
Task list and Todo ideas

### ISSUE THREAD

**Issue by vjetten** [vjetten/openlisem#7]
### TODO
- [ ] Make kinematic wave less dependent on timestep (looping?)
- [ ] Trapezium shaped channel cross sections
- [x] Make a patching system that warns the user there is a new version
- [x] Clean up model.h with better comments and groups of variables and functions. To decide: put all variables up front or variables with corresponing funtions (for instance put infiltration variables and functions in one section?
- [x] Separate model from interface 
- [x] Gridcell retention for overlandflow and channel, also for Kinematic Wave
- [x] Boundary flow in 2D flow
- [ ] automatic runs for Monte carlo stuff and solution finding (see LISEM code Bastian)
- [ ] Integrate Pestice stuff from Meindert in 1D and 2D flow, into main_c
- [x] Test culverts further on behaviour
- [x] Extend culverts to sewage/storm drain flow
- [x] SWOF, check if MUSCL is allowed in this 1st order way or must be 2nd order, look at SWOF code
- [ ] Dynamic wave channel flow
- [ ] Add slope stability
